// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"shorturl/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/convert",
				Handler: ConverHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: StatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/analyze",
				Handler: AnalyzeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/links/categories",
				Handler: LinkCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/links/:id",
				Handler: UpdateLinkHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/links/:id",
				Handler: DeleteLinkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/links",
				Handler: LinkListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:shortURL",
				Handler: ShowHandler(serverCtx),
			},
		},
	)
}
