// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ConverRequest struct {
	LongUrl string `json:"longURL" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortURL"`
}

type ShowRequest struct {
	ShortURL string `path:"shortURL" validate:"required"`
}

type ShowResponse struct {
	LongURL string `json:"longURL"`
}
